//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaProductos.Proyect.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IN04
    {
        public int CodigoProducto { get; set; }
        public string Descripcion { get; set; }
        public double Precio { get; set; }
        public int SaldoInventario { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string UsuarioIngreso { get; set; }
        public int IDFamilia { get; set; }
    
        public virtual IN05 IN05 { get; set; }
    }
}
